/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const LandingPage1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `4282px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Footer = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1280px`,
  height: `649px`,
  left: `0px`,
  top: `3633px`,
  overflow: `hidden`,
});

const Rectangle115 = styled('div')({
  backgroundColor: `rgba(253, 138, 122, 1)`,
  width: `1520px`,
  height: `207px`,
  position: `absolute`,
  left: `0px`,
  top: `442px`,
});

const Vector = styled('img')({
  height: `84px`,
  width: `1050px`,
  position: `absolute`,
  left: `115px`,
  top: `241px`,
});

const Line183 = styled('div')({
  border: `1px solid rgba(216, 255, 62, 1)`,
  width: `401px`,
  height: `0px`,
  position: `absolute`,
  left: `76px`,
  top: `573px`,
});

const Q2023HackathonEthSamSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(216, 255, 62, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Q2023HackathonEthSamSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(216, 255, 62, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Q2023HackathonEthSam = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(216, 255, 62, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `76px`,
  top: `573px`,
});

const OPropósito = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1280px`,
  height: `834px`,
  left: `0px`,
  top: `2799px`,
  overflow: `hidden`,
});

const Frame229 = styled('div')({
  borderRadius: `406px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `750px`,
  height: `755px`,
  left: `-375px`,
  top: `-378px`,
  overflow: `hidden`,
});

const Rectangle71 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `51px`,
  top: `75px`,
});

const Rectangle113 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `-37px`,
  top: `-3px`,
});

const Rectangle87 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `321px`,
  top: `-3px`,
});

const Rectangle79 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `161px`,
  top: `-3px`,
});

const Rectangle88 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `481px`,
  top: `-3px`,
});

const Rectangle75 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `81px`,
  top: `-3px`,
});

const Rectangle89 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `401px`,
  top: `-3px`,
});

const Rectangle80 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `241px`,
  top: `-3px`,
});

const Rectangle90 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `561px`,
  top: `-3px`,
});

const Rectangle73 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `41px`,
  top: `-3px`,
});

const Rectangle91 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `361px`,
  top: `-3px`,
});

const Rectangle81 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `201px`,
  top: `-3px`,
});

const Rectangle92 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `521px`,
  top: `-3px`,
});

const Rectangle76 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `121px`,
  top: `-3px`,
});

const Rectangle93 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `441px`,
  top: `-3px`,
});

const Rectangle82 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `281px`,
  top: `-3px`,
});

const Rectangle94 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `601px`,
  top: `-3px`,
});

const Rectangle106 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `641px`,
  top: `-3px`,
});

const Rectangle107 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `721px`,
  top: `-3px`,
});

const Rectangle108 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `681px`,
  top: `-3px`,
});

const Rectangle109 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `761px`,
  top: `-3px`,
});

const Rectangle111 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `801px`,
  top: `-3px`,
});

const Rectangle114 = styled('div')({
  backgroundColor: `rgba(255, 112, 32, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `821px`,
  top: `-2px`,
});

const Frame230 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `799px`,
  height: `755px`,
  left: `1146px`,
  top: `467px`,
});

const Frame2291 = styled('div')({
  borderRadius: `406px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `750px`,
  height: `755px`,
  left: `905px`,
  top: `522px`,
  overflow: `hidden`,
});

const Rectangle711 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `1px`,
  top: `-3px`,
});

const Rectangle1131 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `-37px`,
  top: `-3px`,
});

const Rectangle871 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `321px`,
  top: `-3px`,
});

const Rectangle791 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `161px`,
  top: `-3px`,
});

const Rectangle881 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `481px`,
  top: `-3px`,
});

const Rectangle751 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `81px`,
  top: `-3px`,
});

const Rectangle891 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `401px`,
  top: `-3px`,
});

const Rectangle801 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `241px`,
  top: `-3px`,
});

const Rectangle901 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `561px`,
  top: `-3px`,
});

const Rectangle731 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `41px`,
  top: `-3px`,
});

const Rectangle911 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `361px`,
  top: `-3px`,
});

const Rectangle811 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `201px`,
  top: `-3px`,
});

const Rectangle921 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `521px`,
  top: `-3px`,
});

const Rectangle761 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `121px`,
  top: `-3px`,
});

const Rectangle931 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `441px`,
  top: `-3px`,
});

const Rectangle821 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `281px`,
  top: `-3px`,
});

const Rectangle941 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `601px`,
  top: `-3px`,
});

const Rectangle1061 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `641px`,
  top: `-3px`,
});

const Rectangle1071 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `721px`,
  top: `-3px`,
});

const Rectangle1081 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `681px`,
  top: `-3px`,
});

const Rectangle1091 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `761px`,
  top: `-3px`,
});

const Rectangle1111 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `801px`,
  top: `-3px`,
});

const Rectangle1141 = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  borderRadius: `20px`,
  width: `20px`,
  height: `868px`,
  position: `absolute`,
  left: `821px`,
  top: `-2px`,
});

const Card = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.9)`,
  borderRadius: `77px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1091px`,
  height: `594px`,
  left: `76px`,
  top: `100px`,
  overflow: `hidden`,
});

const OsMaisNecessitadosNã = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(8, 14, 65, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `300`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `977px`,
  height: `236px`,
  position: `absolute`,
  left: `88px`,
  top: `390px`,
});

const NossoPropósito = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 33, 166, 1)`,
  fontStyle: `normal`,
  fontFamily: `Abel`,
  fontWeight: `400`,
  fontSize: `60px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `389px`,
  top: `49px`,
});

const Vector1 = styled('img')({
  height: `131px`,
  width: `662px`,
  position: `absolute`,
  left: `246px`,
  top: `192px`,
});

const OComo = styled('div')({
  backgroundColor: `rgba(253, 138, 122, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1280px`,
  height: `852px`,
  left: `0px`,
  top: `1947px`,
});

const Vector2 = styled('img')({
  height: `266px`,
  width: `256px`,
  position: `absolute`,
  left: `964px`,
  top: `160px`,
});

const BancosComunitáriosSã = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `400`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `782px`,
  height: `325px`,
  position: `absolute`,
  left: `110px`,
  top: `101px`,
});

const OMicrocréditoÉUmaFor = styled('div')({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `400`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `794px`,
  height: `318px`,
  position: `absolute`,
  left: `243px`,
  top: `485px`,
});

const AFerramenta = styled('div')({
  backgroundColor: `rgba(12, 16, 99, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1280px`,
  height: `1091px`,
  left: `0px`,
  top: `856px`,
  overflow: `hidden`,
});

const SecondParagraph = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `487px`,
  top: `88px`,
});

const AFerramenta1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(239, 94, 65, 1)`,
  fontStyle: `normal`,
  fontFamily: `Abel`,
  fontWeight: `400`,
  fontSize: `60px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const OSocialScoreÉUmaFerr = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `992px`,
  height: `366px`,
  position: `absolute`,
  left: `144px`,
  top: `216px`,
});

const Vector3 = styled('img')({
  height: `244px`,
  width: `586px`,
  position: `absolute`,
  left: `347px`,
  top: `759px`,
});

const SocialScore = styled('div')({
  backgroundColor: `rgba(253, 138, 122, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1280px`,
  height: `856px`,
  left: `0px`,
  top: `0px`,
});

const Frame225 = styled('div')({
  borderRadius: `30px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `434px`,
  height: `92px`,
  left: `444px`,
  top: `511px`,
  overflow: `hidden`,
});

const Rectangle20 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `-15px`,
  top: `6px`,
});

const Rectangle28 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `80px`,
  top: `6px`,
});

const Rectangle36 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `176px`,
  top: `6px`,
});

const Rectangle44 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `272px`,
  top: `6px`,
});

const Rectangle52 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `368px`,
  top: `6px`,
});

const Rectangle60 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `464px`,
  top: `6px`,
});

const Rectangle24 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `33px`,
  top: `6px`,
});

const Rectangle29 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `128px`,
  top: `6px`,
});

const Rectangle37 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `224px`,
  top: `6px`,
});

const Rectangle45 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `320px`,
  top: `6px`,
});

const Rectangle53 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `416px`,
  top: `6px`,
});

const Rectangle61 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `512px`,
  top: `6px`,
});

const Rectangle68 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `560px`,
  top: `7px`,
});

const Rectangle22 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `9px`,
  top: `7px`,
});

const Rectangle32 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `104px`,
  top: `7px`,
});

const Rectangle40 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `200px`,
  top: `7px`,
});

const Rectangle48 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `296px`,
  top: `7px`,
});

const Rectangle56 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `392px`,
  top: `7px`,
});

const Rectangle64 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `488px`,
  top: `7px`,
});

const Rectangle26 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `57px`,
  top: `7px`,
});

const Rectangle33 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `152px`,
  top: `7px`,
});

const Rectangle41 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `248px`,
  top: `7px`,
});

const Rectangle49 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `344px`,
  top: `7px`,
});

const Rectangle57 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `440px`,
  top: `7px`,
});

const Rectangle65 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `536px`,
  top: `7px`,
});

const Rectangle70 = styled('div')({
  backgroundColor: `rgba(216, 255, 62, 1)`,
  width: `11px`,
  height: `127px`,
  position: `absolute`,
  left: `584px`,
  top: `8px`,
});

const Frame223 = styled('div')({
  backgroundColor: `rgba(27, 33, 166, 1)`,
  borderRadius: `30px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `25px 20px 20px 20px`,
  boxSizing: `border-box`,
  left: `463px`,
  top: `522px`,
});

const ConectarCarteira = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(216, 255, 62, 1)`,
  fontStyle: `normal`,
  fontFamily: `Abel`,
  fontWeight: `400`,
  fontSize: `50px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `50px`,
  textTransform: `none`,
  margin: `0px`,
});

const FirstParagraph = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `347px`,
  height: `108px`,
  left: `472px`,
  top: `266px`,
});

const SocialScore1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 251, 244, 1)`,
  fontStyle: `normal`,
  fontFamily: `Abel`,
  fontWeight: `400`,
  fontSize: `75px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `347px`,
  margin: `0px`,
});

const Frame253 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  height: `100px`,
  width: `100px`,
  margin: `60px 0px 0px 0px`,
  overflow: `hidden`,
});

const PontuaçãoSocialParaC = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 33, 166, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto Mono`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `183px`,
  top: `408px`,
});

const Vector4 = styled('img')({
  height: `127.5px`,
  width: `114px`,
  position: `absolute`,
  left: `1116px`,
  top: `78px`,
});

function LandingPage(props) {
  return (
    <LandingPage1 className={props.className}>
      <Footer>
        <Rectangle115></Rectangle115>
        <Vector
          src={`assets/images/LandingPage_Vector.png`}
          loading="lazy"
          alt={'Vector'}
        />
        <Line183></Line183>
        <Q2023HackathonEthSam>
          <Q2023HackathonEthSamSpan1>{`2023 // Hackathon `}</Q2023HackathonEthSamSpan1>
          <Q2023HackathonEthSamSpan2>{`ETH Samba Hack`}</Q2023HackathonEthSamSpan2>
        </Q2023HackathonEthSam>
      </Footer>
      <OPropósito>
        <Frame229>
          <Rectangle71></Rectangle71>
          <Rectangle113></Rectangle113>
          <Rectangle87></Rectangle87>
          <Rectangle79></Rectangle79>
          <Rectangle88></Rectangle88>
          <Rectangle75></Rectangle75>
          <Rectangle89></Rectangle89>
          <Rectangle80></Rectangle80>
          <Rectangle90></Rectangle90>
          <Rectangle73></Rectangle73>
          <Rectangle91></Rectangle91>
          <Rectangle81></Rectangle81>
          <Rectangle92></Rectangle92>
          <Rectangle76></Rectangle76>
          <Rectangle93></Rectangle93>
          <Rectangle82></Rectangle82>
          <Rectangle94></Rectangle94>
          <Rectangle106></Rectangle106>
          <Rectangle107></Rectangle107>
          <Rectangle108></Rectangle108>
          <Rectangle109></Rectangle109>
          <Rectangle111></Rectangle111>
          <Rectangle114></Rectangle114>
        </Frame229>
        <Frame230></Frame230>
        <Frame2291>
          <Rectangle711></Rectangle711>
          <Rectangle1131></Rectangle1131>
          <Rectangle871></Rectangle871>
          <Rectangle791></Rectangle791>
          <Rectangle881></Rectangle881>
          <Rectangle751></Rectangle751>
          <Rectangle891></Rectangle891>
          <Rectangle801></Rectangle801>
          <Rectangle901></Rectangle901>
          <Rectangle731></Rectangle731>
          <Rectangle911></Rectangle911>
          <Rectangle811></Rectangle811>
          <Rectangle921></Rectangle921>
          <Rectangle761></Rectangle761>
          <Rectangle931></Rectangle931>
          <Rectangle821></Rectangle821>
          <Rectangle941></Rectangle941>
          <Rectangle1061></Rectangle1061>
          <Rectangle1071></Rectangle1071>
          <Rectangle1081></Rectangle1081>
          <Rectangle1091></Rectangle1091>
          <Rectangle1111></Rectangle1111>
          <Rectangle1141></Rectangle1141>
        </Frame2291>
        <Card>
          <OsMaisNecessitadosNã>
            {`Os mais necessitados não têm acesso ao sistema financeiro, e um dos motivos é não existir uma métrica para o histórico de bons pagadores fora do sistema financeiro tradicional, mas com os mesmos padrões de segurança.`}
          </OsMaisNecessitadosNã>
          <NossoPropósito>{`Nosso Propósito`}</NossoPropósito>
          <Vector1
            src={`assets/images/LandingPage_Vector_1.png`}
            loading="lazy"
            alt={'Vector'}
          />
        </Card>
      </OPropósito>
      <OComo>
        <Vector2
          src={`assets/images/LandingPage_Vector_2.png`}
          loading="lazy"
          alt={'Vector'}
        />
        <BancosComunitáriosSã>
          {`Bancos comunitários são instituições financeiras que têm como objetivo atender às necessidades financeiras das comunidades em que estão inseridos, principalmente aquelas que têm dificuldades em acessar serviços financeiros tradicionais, como em áreas de baixa renda ou regiões rurais. Eles buscam promover a inclusão financeira, a economia local e o desenvolvimento social e econômico das comunidades em que atuam.`}
        </BancosComunitáriosSã>
        <OMicrocréditoÉUmaFor>
          {`O microcrédito é uma forma de empréstimo oferecida pelos bancos comunitários para atender às necessidades financeiras de pessoas de baixa renda que desejam iniciar atividades produtivas, mas têm dificuldades em acessar empréstimos tradicionais. O processo de concessão de microcrédito envolve uma análise da capacidade de pagamento do cliente, oferecendo taxas de juros mais baixas do que as instituições financeiras tradicionais.`}
        </OMicrocréditoÉUmaFor>
      </OComo>
      <AFerramenta>
        <SecondParagraph>
          <AFerramenta1>{`A Ferramenta`}</AFerramenta1>
        </SecondParagraph>
        <OSocialScoreÉUmaFerr>
          {`O SocialScore é uma ferramenta de pontuação social para avaliar a capacidade de pagamento dos clientes dos bancos comunitários com base em critérios que vão além do histórico de crédito convencional. 

O score social pode incluir fatores como o envolvimento do cliente na comunidade, o impacto social e ambiental de suas atividades produtivas e a capacidade de geração de renda para a família. Com essa ferramenta, os bancos comunitários podem avaliar o risco de conceder empréstimos de microcrédito de forma mais precisa e justa, ao mesmo tempo em que consideram os aspectos sociais e econômicos relevantes para a comunidade.`}
        </OSocialScoreÉUmaFerr>
        <Vector3
          src={`assets/images/LandingPage_Vector_3.png`}
          loading="lazy"
          alt={'Vector'}
        />
      </AFerramenta>
      <SocialScore>
        <Frame225>
          <Rectangle20></Rectangle20>
          <Rectangle28></Rectangle28>
          <Rectangle36></Rectangle36>
          <Rectangle44></Rectangle44>
          <Rectangle52></Rectangle52>
          <Rectangle60></Rectangle60>
          <Rectangle24></Rectangle24>
          <Rectangle29></Rectangle29>
          <Rectangle37></Rectangle37>
          <Rectangle45></Rectangle45>
          <Rectangle53></Rectangle53>
          <Rectangle61></Rectangle61>
          <Rectangle68></Rectangle68>
          <Rectangle22></Rectangle22>
          <Rectangle32></Rectangle32>
          <Rectangle40></Rectangle40>
          <Rectangle48></Rectangle48>
          <Rectangle56></Rectangle56>
          <Rectangle64></Rectangle64>
          <Rectangle26></Rectangle26>
          <Rectangle33></Rectangle33>
          <Rectangle41></Rectangle41>
          <Rectangle49></Rectangle49>
          <Rectangle57></Rectangle57>
          <Rectangle65></Rectangle65>
          <Rectangle70></Rectangle70>
        </Frame225>
        <Frame223>
          <ConectarCarteira>{`CONECAR CARTEIRA`}</ConectarCarteira>
        </Frame223>
        <FirstParagraph>
          <SocialScore1>{`SocialScore`}</SocialScore1>
          <Frame253></Frame253>
        </FirstParagraph>
        <PontuaçãoSocialParaC>
          {`pontuação social para clientes de bancos comunitários`}
        </PontuaçãoSocialParaC>
        <Vector4
          src={`assets/images/LandingPage_Vector_4.png`}
          loading="lazy"
          alt={'Vector'}
        />
      </SocialScore>
    </LandingPage1>
  );
}

export default LandingPage;
